[package]
name = "defeat"
version = "0.1.0"
authors = ["Armin Ronacher <armin.ronacher@active-4.com>"]

[dependencies]
backtrace = { version = "0.3.9", optional = true }

[features]
default = ["backtrace"]
